### PR TITLE
Stephen getting started

### PR DESCRIPTION
**Pull request by stktung**

### CODE REVIEW

**Comment by tomthetrainer** [comment]
Stephen, 

I had some troubles getting codespaces to follow the link output by the start_cluster.sh command. 


Can we add the following line, in the output of the start_cluster.sh script. 


right after, 
"Browse the EventStoreDB Admin UI at .... "

If you have trouble opening that link please see the PDF, 
"Instructions for Running in Codespaces" for an alternate way to access the webui for EventstoreDB

**Comment by tomthetrainer** [comment]
For the .devcontainer configurations. 

.devcontainer/quickstart/devcontainer.json

Does that complicate things in any way? 

It looks like you have created two configuration options in the devcontainer. 


.devcontainer/fromscratch
./devcontainer/quickstart


Does the devcontainer config apply only when running in vscode locally or does it affect when running in codespaces. 


I like the idea of a single .devcontainer config, but could use more information on when and where it takes effect. 

A meeting is fine, if text descriptions become cumbersome

**Comment by tomthetrainer** [comment]
Stephen, 

Upon re-run of the .start_cluster.sh

We could use some information on the output, that script sort of got hacked together. It seems to work, but one of us should add..


"Cluster is running" 

"That cluster will be stopped and removed" 
"A new cluster will be started" 
"Any previous data written will be lost, this is by design"

**Comment by stktung** [comment]
> Stephen,
> 
> I had some troubles getting codespaces to follow the link output by the start_cluster.sh command.
> 
> Can we add the following line, in the output of the start_cluster.sh script.
> 
> right after, "Browse the EventStoreDB Admin UI at .... "
> 
> If you have trouble opening that link please see the PDF, "Instructions for Running in Codespaces" for an alternate way to access the webui for EventstoreDB

Would like to dig deeper into the problem you experienced. Let's talk offline

**Comment by stktung** [comment]
> For the .devcontainer configurations.
> 
> .devcontainer/quickstart/devcontainer.json
> 
> Does that complicate things in any way?
> 
> It looks like you have created two configuration options in the devcontainer.
> 
> .devcontainer/fromscratch ./devcontainer/quickstart
> 
> Does the devcontainer config apply only when running in vscode locally or does it affect when running in codespaces.
> 
> I like the idea of a single .devcontainer config, but could use more information on when and where it takes effect.
> 
> A meeting is fine, if text descriptions become cumbersome

What you said is reason, but let me explain this with you offline first.

In short, there were a few small things I'd like to achieve in quickstart (e.g. don't open README.md by default ) that is shouldn't apply to the from scratch. But let's see how we can sort out what you mentioned.

**Comment by stktung** [comment]
> Stephen,
> 
> Upon re-run of the .start_cluster.sh
> 
> We could use some information on the output, that script sort of got hacked together. It seems to work, but one of us should add..
> 
> "Cluster is running"
> 
> "That cluster will be stopped and removed" "A new cluster will be started" "Any previous data written will be lost, this is by design"

Can do! I'll work on it some time this week.

**Pull request merged**
